spring:
  application:
    name: spring-web-reactive
  r2dbc:
    url: r2dbc:postgresql://localhost:5448/reactive-db
    username: root
    password: root
  flyway:
    url: jdbc:postgresql://localhost:5448/reactive-db
    user: root
    password: root

jwt:
  secret: 0fe6555df15108eecb61b1794c99a77db7186ee892d7e992a299a388224917c0
  expiration: 30m

logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG